/// Every user-facing string. One file so a pt-PT pass later is one edit.
enum Strings {
    static let appName = "Voice"
    static let idle = "Ready — hold Fn to dictate"
    static let listening = "Listening…"
    static let transcribing = "Transcribing…"
    static let cleaning = "Cleaning…"
    static let done = "Done"
    static let nothingHeard = "Nothing heard"
    static let cancelled = "Cancelled"
    static let pastedRaw = "Pasted raw — server slow or offline"
    static let tokenInvalid = "Token invalid — open Settings"
    static let secureField = "Secure field — text copied to clipboard instead"
    static let modelLoading = "Model loading"
    static let modelNotDownloaded = "Model not downloaded"
    static let copyLast = "Copy last dictation"
    static let pause = "Pause dictation"
    static let resume = "Resume dictation"
    static let settings = "Settings…"
    static let quit = "Quit Voice"
    static let mode = "Mode"
    static let language = "Language"
    static let modeClean = "Clean"
    static let modeLiteral = "Literal"
    static let langAuto = "Auto"
    static let langPt = "Português"
    static let langEn = "English"

    static let setUpPermissions = "Set up permissions…"
    static let modelReady = "Model: ready"
    static func modelError(_ message: String) -> String { "Model error: \(message)" }
    static let modelLabelTurbo = "Large v3 Turbo (compressed, 630 MB) — recommended"
    static let modelLabelLarge = "Large v3 Turbo (full, ~1.5 GB) — maximum accuracy"

    // Onboarding
    static let onboardingTitle = "Set up Voice"
    static let permMicrophone = "Microphone"
    static let permInputMonitoring = "Input Monitoring (to see the Fn key)"
    static let permAccessibility = "Accessibility (to paste with ⌘V)"
    static let permFnKeyboard = "Keyboard › Press 🌐 key to → Do Nothing"
    static let onboardingRelaunchNote = "Some grants only take effect after a relaunch."
    static let relaunch = "Relaunch"
    static let onboardingDone = "Done"
}
