/// Every user-facing string. One file so a pt-PT pass later is one edit.
enum Strings {
    static let appName = "Voice"
    static let idle = "Ready — hold Fn to dictate"
    static let listening = "Listening…"
    static let transcribing = "Transcribing…"
    static let cleaning = "Cleaning…"
    static let done = "Done"
    static let nothingHeard = "Nothing heard"
    static let cancelled = "Cancelled"
    static let pastedRaw = "Pasted raw — server slow or offline"
    static let tokenInvalid = "Token invalid — open Settings"
    static let secureField = "Secure field — text copied to clipboard instead"
    static let modelLoading = "Model loading"
    static let modelNotDownloaded = "Model not downloaded"
    static let copyLast = "Copy last dictation"
    static let pause = "Pause dictation"
    static let resume = "Resume dictation"
    static let settings = "Settings…"
    static let quit = "Quit Voice"
    static let mode = "Mode"
    static let language = "Language"
    static let modeClean = "Clean"
    static let modeLiteral = "Literal"
    static let langAuto = "Auto"
    static let langPt = "Português"
    static let langEn = "English"
}
