#!/usr/bin/env python3
"""
Generates `Voice/UI/SpitMarkGrid.swift` from the recording mark in `mac/branding/spit-recording.png`.

Run after changing the mark:

    python3 mac/scripts/make-spit-mark.py && cd mac && xcodegen generate

The mark is dot-matrix art on an 8 px grid, and it is drawn inside the 22 pt mic button, where one
of its dots is about a third of a point. Shipping the PNG and letting AppKit scale it would work,
but it would bake in the colour (off-white, invisible on the light-mode bar) and give the view no
way to address the sound-wave arcs separately, which is what lets them follow the voice. So the
grid is read back into rows of text and the view draws the dots itself.
"""

from pathlib import Path
import sys

from PIL import Image

ROOT = Path(__file__).resolve().parent.parent          # mac/
SRC = ROOT / "branding" / "spit-recording.png"
OUT = ROOT / "Voice" / "UI" / "SpitMarkGrid.swift"

CELL = 8                      # every cell of the mark is an 8x8 block, either ink or transparent


def main() -> None:
    if not SRC.exists():
        sys.exit(f"missing source mark: {SRC}")
    mark = Image.open(SRC).convert("RGBA")
    if mark.width % CELL or mark.height % CELL:
        sys.exit(f"expected a mark on a {CELL} px grid, got {mark.size}")

    rows = []
    for gy in range(mark.height // CELL):
        row = ""
        for gx in range(mark.width // CELL):
            alphas = {mark.getpixel((gx * CELL + dx, gy * CELL + dy))[3]
                      for dx in range(CELL) for dy in range(CELL)}
            # A cell that is part ink, part clear means the grid assumption is wrong, and the
            # rows would silently shift or drop dots.
            if len(alphas) > 1:
                sys.exit(f"cell ({gx}, {gy}) is not a solid {CELL}x{CELL} block — is the mark still on a {CELL} px grid?")
            row += "#" if alphas == {255} else "."
        rows.append(row)

    body = "\n".join(f'        "{r}",' for r in rows)
    OUT.write_text(f"""// Generated by mac/scripts/make-spit-mark.py from mac/branding/spit-recording.png — do not edit.

enum SpitMarkGrid {{
    /// One string per row of the mark, top to bottom; `#` is a dot.
    static let rows: [String] = [
{body}
    ]
}}
""")
    print(f"wrote {len(rows)} rows to {OUT.relative_to(ROOT.parent)}")


if __name__ == "__main__":
    main()
